version: '3'
services:
  web:
    build:
      context: ./build/web
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080

  db:
    build:
      context: ./build/db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-data:
    driver: local